# Generated by Django 4.2.13 on 2024-06-18 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyArtistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('spotify_artist', models.CharField(max_length=100, unique=True)),
                ('spotify_image', models.URLField(blank=True)),
                ('spotify_popularity', models.PositiveIntegerField(blank=True)),
                ('spotify_artist_albums_registered', models.PositiveIntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('twitter_handle', models.CharField(max_length=20, unique=True)),
                ('twitter_name', models.CharField(max_length=100)),
                ('twitter_user_id', models.PositiveIntegerField(unique=True)),
                ('twitter_handle_avatar', models.URLField(blank=True)),
                ('twitter_last_post_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TwitterUserPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('twitter_post_type', models.CharField(max_length=20)),
                ('twitter_post_id', models.PositiveIntegerField(unique=True)),
                ('twitter_text', models.TextField(max_length=20)),
                ('twitter_post_to_link', models.URLField(blank=True)),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='centralHub.twitteruser')),
            ],
            options={
                'unique_together': {('twitter_user', 'twitter_text')},
            },
        ),
        migrations.CreateModel(
            name='SpotifyAlbumTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('spotify_albums', models.CharField(max_length=200)),
                ('number_of_tracks', models.PositiveIntegerField(blank=True)),
                ('spotify_image_url', models.URLField(blank=True)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_album', to='centralHub.spotifyartistinfo')),
            ],
            options={
                'unique_together': {('spotify_user', 'spotify_albums')},
            },
        ),
    ]
