# Generated by Django 4.2.13 on 2024-05-31 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("centralHub", "0002_twitteruser_twitter_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twitteruser",
            name="twitter_name",
        ),
    ]
