# Generated by Django 4.2.13 on 2024-06-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "centralHub",
            "0009_rename_spotify_tracks_spotifyalbumtracking_number_of_tracks",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyartistinfo",
            name="spotify_artist_albums_registered",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
