# Generated by Django 4.2.12 on 2024-06-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralHub', '0011_alter_spotifyalbumtracking_spotify_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='twitter_last_post_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
