# Generated by Django 4.2.12 on 2024-06-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralHub', '0013_alter_twitteruser_twitter_last_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyartistinfo',
            name='spotify_artist_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
