# Generated by Django 4.2.12 on 2024-06-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centralHub", "0007_remove_spotifyartistinfo_spotify_albums_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifyartistinfo",
            name="spotify_image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="spotifyartistinfo",
            name="spotify_popularity",
            field=models.PositiveIntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
