# Generated by Django 4.2.12 on 2024-06-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centralHub', '0015_alter_spotifyartistinfo_spotify_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyartistinfo',
            name='spotify_artist_id',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
