# Generated by Django 4.2.12 on 2024-06-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centralHub", "0017_alter_twitteruser_twitter_last_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitteruser",
            name="twitter_last_post_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
