# Generated by Django 4.2.12 on 2024-07-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centralHub", "0018_alter_twitteruser_twitter_last_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twitteruser",
            name="twitter_last_post_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="twitteruser",
            name="twitter_user_id",
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="twitteruserposts",
            name="twitter_post_id",
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
