# Generated by Django 4.2.12 on 2024-05-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centralHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterframework',
            old_name='twitter_handle_link',
            new_name='twitter_post_to_link',
        ),
        migrations.RenameField(
            model_name='twitterframework',
            old_name='twitter_handle_post_type',
            new_name='twitter_post_type',
        ),
    ]
